### ISSUE TITLE
awscli issues with conda-forge on OSX-64

### ISSUE THREAD

**Issue by blackbox-tech** [conda-forge/awscli-feedstock#718]
I'm having issues with several conda-forge packages in osx-64 which install without problems on linux.  Specifically one package that I can't get to install on osx-64 is the **awscli** (the Amazon Web Services cmd-line interface). 

I've had to attach the steps to reproduce this issue [in a separate gist](https://gist.github.com/blackbox-tech/965061ebb6b7c776a1dab48eba028e04) because I can't post them in this github issue as the conda output is > 64K.

How do I go about resolving all these conflicts?   I've tried updating conda/python using flexible channel_priority and prepending the conda-forge channel instead of appending it, but nothing seems to work.   

I don't know how maintains this recipe or how to contact them to fix it?  However, I suspect this is may not be an issue with the **awscli** recipe but a problem in one of its downstream dependencies that is causing major problems for conda-forge users on osx-64.

As I mentioned above the **awscli** package installs without problems on linux with both python 3.7 or 3.8.  My current constraint to python3.7 on osx-64 is because of Tensorflow's current conda-forge dependencies on osx-64.  

Is there a work around while these issues on osx-64 are investigated and fixed, for example is the **awscli** known to work on an older version of conda on osx-64 in the past which I could downgrade to, or will that not help?

**Comment by jakirkham** [comment]
I've transferred this to the appropriate feedstock. In the future would search the conda-forge GitHub org for the package name and raise the issue on the corresponding feedstock.

**Comment by tkelman** [comment]
what does `--clone base` do? is it actually an empty environment with that argument? there are several upper bounds that come from upstream on dependency versions here with awscli. something that you've got installed in your base environment might not have a version available that's consistent with those upper bounds? or the resolver isn't allowed to downgrade those packages for some reason?

**Comment by blackbox-tech** [comment]
'base' is just the default anaconda environment.  Nothing has been installed in it, but it has been downgraded from python 3.7 to python 3.8 as described.

I've also tried the following:
```
$ conda create --name another_env python=3.7
$ conda activate another_env 
$ conda install awscli
```
but on osx it gets stuck after a couple of hours after finding hundreds of conflicts.  The same commands works successfully on linux however.

Is anyone else able to reproduce this?  I also tried blasting my ~/opt/anaconda3 installation, and my ~/.conda folder, then reinstalling everything again but I hit the same problem (on osx).

**Comment by tkelman** [comment]
I don't have access to a mac or a whole lot of time to debug this. The mac CI passes here, I'm not sure what's different between what it runs and what you're seeing with installing a fresh environment.

**Comment by blackbox-tech** [comment]
If no one else can test it I'll ask a colleague to try on their laptop.

**Comment by chrisburr** [comment]
The solver in [mamba](https://github.com/mamba-org/mamba/) is much faster generally does a better job of explaining errors things. You basically do everything as normal but replace the three commands `conda install`/`conda create`/`conda env create` with `mamba install`/`mamba create`/`mamba env create`. In this case:

```bash
# Install mamba in the base environment
conda install --name base mamba
# Now try debugging
mamba create --name another_env python=3.7
conda activate another_env 
mamba install awscli
```

**Comment by blackbox-tech** [comment]
@tkelman I think there might be something borked with my macbook, even after doing a full anaconda reinstall.  Let's close this issue for now and not waste time on it, I'll report back if I get stuck again, but I suspect this is not a real issue.
